### PR TITLE
Tilt-compensated heading

### LINKED ISSUE #188: SailBot: Heading is wrong when tilted
The driver of the magnetometer does not take into account the tilt of the boat, which results in the wrong heading reading when the boat is tilted. This issue aims at improving the driver to either:

* recognize the boat tilt from the IMU and return invalid reading
* compensate for the boat tilt and return valid magnetometer reading even though the boat is tilted

### PR DESCRIPTION
**Pull request by malishav**
The PR modifies LIS2MDL API to offer both uncompensated and tilt-compensated heading. I modify the example project of LIS2MDL to show how to use the tilt-compensated heading together with roll and pitch readings from the accelerometer.

Fixes #188

### CODE REVIEW

**Review by aabadie — COMMENTED** [review]
(I know this is still WIP but I have a high level comment)

It seems strange to me that the lis2mdl driver - which is just magnetometer after all - has code to compute the heading and that, with this PR, has a dependency to another sensor driver.

I would prefer a different approach: let the lis2mdl just return a tuple of raw magnetometer values (x,y,z), same for lsm3ds with accelerometer/gyroscope values. And add on top of both sensor drivers a `drv` library to compute the heading (compensated and uncompensated). That will be reusability for different purposes of the magnetometer and accelerometer/gyroscope sensor drivers while still providing a more focused API for heading computation.

**Comment by malishav** [comment]
I think that [1695a8b](https://github.com/DotBots/DotBot-firmware/pull/204/commits/1695a8b2e3453d57bb72b5b6022864dd12e834f8) addresses your comments. Could you check?

**Review by aabadie — CHANGES_REQUESTED** [review]
Some inline comments.

One comment about the imu API, can we add an `imu_init` function that would basically call `lis2mdl_init` and `lsm3ds_init` inside ?

**Comment by malishav** [comment]
@aabadie the compensation algorithm seems to work, just tested on a SailBot. there is a more general problem with calibration of the compass, as the offset values are really only fit for the REV 1.0 board *inside* the SailBot chassis, and I was testing with a board outside of the chassis, which caused some confusion.

**Review by aabadie — APPROVED** [review]
All my previous comments have been addressed and the new code is working. We can improve later if needed.

**Pull request merged**
